export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  NOT_FOUND = 'NOT_FOUND',

  BAD_REQUEST = 'BAD_REQUEST',

  UNAUTHORIZED = 'UNAUTHORIZED',

  FORBIDDEN = 'FORBIDDEN',

  CONFLICT = 'CONFLICT',

  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}